version: '2'

services:
  postgres:
    extends:
      file: docker-compose-common.yml
      service: postgres
    restart: always

  api:
    extends:
      file: docker-compose-common.yml
      service: api-production
    command: uwsgi --emperor uwsgi.ini
    depends_on:
      - postgres

  nginx:
    extends:
      file: docker-compose-common.yml
      service: nginx
    ports:
      - "80:80"