# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-08 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cube',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimension', models.IntegerField(verbose_name='nombre')),
                ('matrix', models.TextField(verbose_name='matrix')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'cube',
                'verbose_name_plural': 'cubes',
            },
        ),
    ]
